[package]
name = "terminal-spinners"
description = "A library for showing terminal loading animations"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/SirWindfield/terminal-spinners-rs"
version = "0.1.0"
authors = ["SirWindfield <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[dependencies]
crossterm = { version = "0.19.0", optional = true }
crossbeam-utils = { version = "0.8", optional = true }
terminal-emoji = "0.3.0"

[build-dependencies]
anyhow = "1.0.38"
heck = "0.3.2"
quote = "1.0.9"
serde = {version = "1.0.123", features = ["derive"]}
serde_json = "1.0.64"

[features]
default = ["print"]
print = ["crossterm", "crossbeam-utils"]
