[package]
name = "terminal-spinners"
version = "0.1.0"
authors = ["SirWindfield <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
anyhow = "1.0.38"
heck = "0.3.2"
quote = "1.0.9"
serde = {version = "1.0.123", features = ["derive"]}
serde_json = "1.0.64"
