[package]
name = "terminal-spinners"
description = "A library for showing terminal loading animations"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/SirWindfield/terminal-spinners-rs"
version = "0.1.3"
authors = ["SirWindfield <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[dependencies]
crossterm = { version = "0.19.0", optional = true }
terminal-log-symbols = "0.1.5"
terminal-spinner-data = "0.1.0"

[features]
default = ["print"]
print = ["crossterm"]
